name: bandit-security-linter
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v2
      - name: Run bandit
        uses: tj-actions/bandit@67ccda81837995c1e194e7b010f5ec55e762f204 # v5.1
        with:
          options: "-c bandit.yml -r"
