name: build

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ '**.md', 'docs/**' ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.13", "3.12", "3.11", "3.10", "3.9", "3.8"]

    runs-on: ${{ matrix.os }}
    permissions:
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install pip==25.0
        pip install pipenv==2024.4.1
        # use --pre flag to enable use of prerelease package versions
        pipenv install
        pipenv install pytest==8.3.5 coverage==7.6.10
    - name: Test with pytest
      env:
          # This token is provided by Actions,
          # you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pipenv run coverage run -m pytest
        pipenv run coverage xml -o coverage/python.xml
