name: build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Set up Python 3.9
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        # use --pre flag to enable use of prerelease package versions
        pipenv install
        pipenv install pytest coverage
    - name: Test with pytest
      env:
          # This token is provided by Actions,
          # you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pipenv run coverage run -m pytest
        pipenv run coverage xml -o coverage/python.xml
