name: build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        pip install pip==25.0
        pip install pipenv==2024.4.1
        # use --pre flag to enable use of prerelease package versions
        pipenv install
        pipenv install pytest==8.3.4 coverage==7.6.10
    - name: Test with pytest
      env:
          # This token is provided by Actions,
          # you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pipenv run coverage run -m pytest
        pipenv run coverage xml -o coverage/python.xml
