name: build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        pip install -r .github/requirements/build.txt
        pipenv install --dev
    - name: Test with pytest
      env:
          # This token is provided by Actions,
          # you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pipenv run coverage run -m pytest
        pipenv run coverage xml -o coverage/python.xml
