name: Malcontent Malware Analysis
on:
  pull_request:

jobs:
  malcontent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@93bad3a2bbadfec044b6ec423d740686d8f00d50 # v0.3
        with:
          fetch-depth: 0
      
      - uses: chainguard-dev/malcontent-action...
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
