name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
       # 'id-token: write' is mandatory for trusted publishing
       # see: https://docs.pypi.org/trusted-publishers/
       id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r ./github/requirements/python-publish.txt
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
