name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
       # 'id-token: write' is mandatory for trusted publishing
       # see: https://docs.pypi.org/trusted-publishers/
       id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install build==1.2.2.post1
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
